remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: MS-EVS Dataset
description: Mutlispectral Event-based Dataset for Face Detection
